#!/usr/bin/env python3
"""Offline generator for the authoritative GAT1 fixed-point aim table."""

from __future__ import annotations

import argparse
import base64
import hashlib
import math
import pathlib
import struct

MAGIC = b"GAT1"
VERSION = 1
ENTRY_COUNT = 4096
QUARTER_COUNT = ENTRY_COUNT // 4
SCALE = 1_000_000
HEADER = struct.Struct("<4sHHI")
ENTRY = struct.Struct("<ii")


def generate_bytes() -> bytes:
    quarter: list[tuple[int, int]] = []
    for offset in range(QUARTER_COUNT):
        angle = (math.pi * 0.5 * offset) / QUARTER_COUNT
        quarter.append((round(math.cos(angle) * SCALE), round(math.sin(angle) * SCALE)))

    entries: list[tuple[int, int]] = []
    for index in range(ENTRY_COUNT):
        quadrant, offset = divmod(index, QUARTER_COUNT)
        x, y = quarter[offset]
        if quadrant == 0:
            direction = (x, y)
        elif quadrant == 1:
            direction = (-y, x)
        elif quadrant == 2:
            direction = (-x, -y)
        else:
            direction = (y, -x)
        entries.append(direction)

    payload = bytearray(HEADER.pack(MAGIC, VERSION, ENTRY_COUNT, SCALE))
    for x, y in entries:
        payload.extend(ENTRY.pack(x, y))
    return bytes(payload)


def render_gdscript(data: bytes) -> bytes:
    encoded = base64.b64encode(data).decode("ascii")
    chunks = [encoded[index:index + 100] for index in range(0, len(encoded), 100)]
    expressions = "\n".join(
        f'\t{"" if index == 0 else "+ "}"{chunk}"'
        for index, chunk in enumerate(chunks)
    )
    sha256 = hashlib.sha256(data).hexdigest()
    source = (
        "# Generated by generate_aim_table.py. Do not hand-edit.\n"
        "extends RefCounted\n\n"
        f"const BYTE_LENGTH := {len(data)}\n"
        f'const CANONICAL_SHA256 := \"{sha256}\"\n'
        "const ENCODED_BASE64 := (\n"
        f"{expressions}\n"
        ")\n\n"
        "static func canonical_bytes() -> PackedByteArray:\n"
        "\treturn Marshalls.base64_to_raw(ENCODED_BASE64)\n"
    )
    return source.encode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()
    data = generate_bytes()
    resource = render_gdscript(data)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(resource)
    print(
        f"canonical_bytes={len(data)} entries={ENTRY_COUNT} "
        f"canonical_sha256={hashlib.sha256(data).hexdigest()} "
        f"resource_bytes={len(resource)} resource_sha256={hashlib.sha256(resource).hexdigest()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
