extends RefCounted

const Contracts := preload("res://better_spewing/contracts/goo_contracts.gd")

const SCHEMA_VERSION := 1
const HASH_BYTE_COUNT := 32

# The order in this descriptor is the serialized byte order. Array entry
# schemas are listed immediately after their ordered length-prefixed array.
const FIELD_ORDER := [
	"schema_version:u16",
	"tick:u32",
	"ledger.initial:i64",
	"ledger.reserve:i64",
	"ledger.airborne:i64",
	"ledger.settled:i64",
	"ledger.suction:i64",
	"ledger.recovery_queue:i64",
	"ledger.drain:i64",
	"packets:array<packet>:stable_id",
	"packet.id:u32",
	"packet.position_x_fp:i32",
	"packet.position_y_fp:i32",
	"packet.velocity_x_fp_per_s:i32",
	"packet.velocity_y_fp_per_s:i32",
	"packet.volume_q:u16",
	"packet.lifetime_ticks:u16",
	"packet.lifecycle:u8",
	"packet.suction_reserved:bool8",
	"packet.stationary_ticks:u16",
	"packet.position_x_remainder:i32",
	"packet.position_y_remainder:i32",
	"packet.gravity_remainder:i32",
	"settled_cells:array<u16>:row_major",
	"active_queue:array<u32>:fifo",
	"active_membership:bytes:row_major_bitset",
	"cell_stable_counters:array<u16>:row_major",
	"suction_jobs:array<suction_job>:stable_id",
	"suction_job.id:u32",
	"suction_job.source_type:u8",
	"suction_job.source_id:u32",
	"suction_job.source_cell_id:u32",
	"suction_job.source_x_fp:i32",
	"suction_job.source_y_fp:i32",
	"suction_job.amount_q:u16",
	"suction_job.start_tick:u32",
	"suction_job.arrival_tick:u32",
	"suction_job.lifecycle:u8",
	"drain_queue:array<drain_record>:fifo",
	"drain_record.id:u32",
	"drain_record.amount_q:u16",
	"drain_record.return_tick:u32",
	"drain_record.lifecycle:u8",
	"recovery_queue:array<recovery_record>:fifo",
	"recovery_record.id:u32",
	"recovery_record.amount_q:u16",
	"recovery_record.arrival_tick:u32",
	"hazards:array<hazard_state>:hazard_id",
	"hazard_state.id:u32",
	"hazard_state.safe:bool8",
	"hazard_state.column_depth_numerators:array<u32>:column_order",
	"next_ids.packet:u32",
	"next_ids.suction_job:u32",
	"next_ids.drain_record:u32",
	"next_ids.recovery_record:u32",
	"remainders.spew_rate:i32",
	"remainders.gulp_rate:i32",
	"remainders.drain_return:i32",
	"remainders.player_gravity:i32",
	"remainders.player_position_x:i32",
	"remainders.player_position_y:i32",
	"remainders.player_recoil_x:i32",
	"remainders.player_recoil_y:i32",
	"player.position_x_fp:i32",
	"player.position_y_fp:i32",
	"player.velocity_x_fp_per_s:i32",
	"player.velocity_y_fp_per_s:i32",
	"player.grounded:bool8",
	"player.movement_state:u8",
	"player.immersion_state:u8",
	"player.submerged_numerator:u32",
	"player.immersion_samples:array<u16>:feet_to_head",
	"player.swim_entry_counter:u8",
	"player.swim_exit_counter:u8",
	"player.recoil_x_fp_per_s:i32",
	"player.recoil_y_fp_per_s:i32",
	"player.last_valid_aim:u16",
	"player.facing:i8",
	"player.current_goo_action:u8",
	"player.action_released:bool8",
	"command_sampler.last_tick:u32",
	"command_sampler.last_move_x:i8",
	"command_sampler.last_move_y:i8",
	"command_sampler.jump_was_down:bool8",
	"command_sampler.spew_was_down:bool8",
	"command_sampler.gulp_was_down:bool8",
	"command_sampler.resolved_action:u8",
	"command_sampler.last_valid_aim:u16",
	"command_sampler.facing:i8",
	"command_sampler.spew_rate_remainder:u16",
	"command_sampler.gulp_rate_remainder:u16",
	"immutable_hashes.room_definition:bytes32",
	"immutable_hashes.tuning:bytes32",
	"immutable_hashes.occupancy:bytes32",
]

const SECTION_9_3_AUDIT := {
	"tick": ["tick"],
	"ledger_categories": ["ledger.initial", "ledger.reserve", "ledger.airborne", "ledger.settled", "ledger.suction", "ledger.recovery_queue", "ledger.drain"],
	"packets_sorted_by_stable_id": ["packets", "packet.id"],
	"settled_cells_row_major": ["settled_cells"],
	"suction_jobs_sorted_by_stable_id": ["suction_jobs", "suction_job.id"],
	"drain_and_recovery_fifo": ["drain_queue", "recovery_queue"],
	"hazard_bits_in_id_order": ["hazards", "hazard_state.id", "hazard_state.safe"],
	"active_fifo_membership_and_counters": ["active_queue", "active_membership", "cell_stable_counters"],
	"all_next_stable_ids": ["next_ids.packet", "next_ids.suction_job", "next_ids.drain_record", "next_ids.recovery_record"],
	"all_fixed_point_remainders": ["remainders", "packet.position_x_remainder", "packet.position_y_remainder", "packet.gravity_remainder"],
	"packet_future_state": ["packet.position_x_fp", "packet.position_y_fp", "packet.velocity_x_fp_per_s", "packet.velocity_y_fp_per_s", "packet.lifetime_ticks", "packet.lifecycle", "packet.stationary_ticks"],
	"player_transform_velocity_grounded_movement": ["player.position_x_fp", "player.position_y_fp", "player.velocity_x_fp_per_s", "player.velocity_y_fp_per_s", "player.grounded", "player.movement_state"],
	"player_immersion_and_recoil": ["player.immersion_state", "player.submerged_numerator", "player.immersion_samples", "player.recoil_x_fp_per_s", "player.recoil_y_fp_per_s"],
	"immersion_hysteresis_counters": ["player.swim_entry_counter", "player.swim_exit_counter"],
	"aim_facing_action_release": ["player.last_valid_aim", "player.facing", "player.current_goo_action", "player.action_released"],
	"command_sampler_future_state": ["command_sampler"],
	"immutable_input_hashes": ["immutable_hashes.room_definition", "immutable_hashes.tuning", "immutable_hashes.occupancy"],
}


static func descriptor() -> String:
	return "\n".join(PackedStringArray(FIELD_ORDER))


static func descriptor_hash() -> String:
	return descriptor().sha256_text()


static func default_state() -> Dictionary:
	return {
		"schema_version": SCHEMA_VERSION,
		"tick": 0,
		"ledger": {
			"initial": 0,
			"reserve": 0,
			"airborne": 0,
			"settled": 0,
			"suction": 0,
			"recovery_queue": 0,
			"drain": 0,
		},
		"packets": [],
		"settled_cells": [],
		"active_queue": [],
		"active_membership": PackedByteArray(),
		"cell_stable_counters": [],
		"suction_jobs": [],
		"drain_queue": [],
		"recovery_queue": [],
		"hazards": [],
		"next_ids": {
			"packet": Contracts.FIRST_STABLE_ID,
			"suction_job": Contracts.FIRST_STABLE_ID,
			"drain_record": Contracts.FIRST_STABLE_ID,
			"recovery_record": Contracts.FIRST_STABLE_ID,
		},
		"remainders": {
			"spew_rate": 0,
			"gulp_rate": 0,
			"drain_return": 0,
			"player_gravity": 0,
			"player_position_x": 0,
			"player_position_y": 0,
			"player_recoil_x": 0,
			"player_recoil_y": 0,
		},
		"player": {
			"position_x_fp": 0,
			"position_y_fp": 0,
			"velocity_x_fp_per_s": 0,
			"velocity_y_fp_per_s": 0,
			"grounded": false,
			"movement_state": Contracts.PlayerMovementState.GROUNDED,
			"immersion_state": Contracts.ImmersionState.DRY,
			"submerged_numerator": 0,
			"immersion_samples": [0, 0, 0, 0, 0],
			"swim_entry_counter": 0,
			"swim_exit_counter": 0,
			"recoil_x_fp_per_s": 0,
			"recoil_y_fp_per_s": 0,
			"last_valid_aim": 0,
			"facing": 1,
			"current_goo_action": Contracts.GooAction.NONE,
			"action_released": true,
		},
		"command_sampler": {
			"last_tick": 0,
			"last_move_x": 0,
			"last_move_y": 0,
			"jump_was_down": false,
			"spew_was_down": false,
			"gulp_was_down": false,
			"resolved_action": Contracts.GooAction.NONE,
			"last_valid_aim": 0,
			"facing": 1,
			"spew_rate_remainder": 0,
			"gulp_rate_remainder": 0,
		},
		"immutable_hashes": {
			"room_definition": _zero_hash(),
			"tuning": _zero_hash(),
			"occupancy": _zero_hash(),
		},
	}


static func _zero_hash() -> PackedByteArray:
	var bytes := PackedByteArray()
	bytes.resize(HASH_BYTE_COUNT)
	bytes.fill(0)
	return bytes
